PAGES_ALLOWED = 'PAGES_ALLOWED'
THREADS_ALLOWED = 'THREADS_ALLOWED'
GITHUB_COMMITS_URL_MASK = 'GITHUB_COMMITS_URL_MASK'
GITHUB_EVENTS_URL_MASK = 'GITHUB_EVENTS_URL_MASK'
DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%SZ'

GITHUB_TYPE_EVENT_FIELD = 'type'
GITHUB_CREATED_AT_EVENT_FIELD = 'created_at'
GITHUB_URL_COMMIT_FIELD = 'url'
GITHUB_STATS_COMMIT_FIELD = 'stats'
GITHUB_ADDITIONS_COMMIT_STATS_FIELD = 'additions'
GITHUB_DELETIONS_COMMIT_STATS_FIELD = 'deletions'

MAXIMUM_PAGES_ALLOWED_ON_GITHUB = 10
